# SOPS configuration for secret management
# 
# Setup:
# 1. Generate an age key: age-keygen -o ~/.config/sops/age/keys.txt
# 2. Get your public key from the generated file
# 3. Replace the example key below with your public key
# 4. Encrypt secrets: sops secrets/example.yaml
# 5. Edit encrypted secrets: sops secrets/example.yaml

creation_rules:
  # Secrets for all systems
  - path_regex: secrets/.*\.yaml$
    age: >-
      age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p
  
  # Host-specific secrets
  - path_regex: secrets/hosts/nixos-laptop/.*\.yaml$
    age: >-
      age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p
  
  - path_regex: secrets/hosts/wsl/.*\.yaml$
    age: >-
      age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p
  
  - path_regex: secrets/hosts/mac-m2/.*\.yaml$
    age: >-
      age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p